### ISSUE TITLE
Practica de Contratos Inteligentes lectura y escritura

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-4y5-tecnopower#1]
[Reporte_De_Practica_4 y5_Desarrollo_De_Contratos_Inteligentes.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-tecnopower/files/8681586/Reporte_De_Practica_4.y5_Desarrollo_De_Contratos_Inteligentes.pdf)

**Comment by christopheremv** [comment]
calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
